### ISSUE TITLE
Amazing

### ISSUE THREAD

**Issue by McGern** [cyanharlow/purecss-francine#1]
Sorry if this is wrong spot to write this, but what you have made is absolutely jaw-dropping and an amazing piece of work!

**Comment by cyanharlow** [comment]
Thank you @McGern , much appreciated!!

**Comment by DiegoHeit** [comment]
That's incredible.... Wow!

**Comment by garfbradaz** [comment]
Same here! I know its a cliché, but I cannot even align text on a screen with CSS! 

Gobsmacked and amazed.

**Comment by gagerandall** [comment]
Masterpiece.

```less
.boob {
    left: 42%;
    width: 24%;
    top: 59%;
    transform: rotate(-9deg);
    box-shadow: 80em 0 60em 26em fade(darken(@dresscolor, 25%), 20%), 0 -50em 40em 26em 
    fade(tint(@dresscolor, 95%), 40%);
}
```
